# See https://redocly.com/docs/cli/configuration/ for more information.
organization: filter
apis:
  onboarding@v1:
    root: ./openapi/OnBoarding_API.json
    labels:
      - onboarding
  account@v1:
    root: ./openapi/Accounting_API.json
    labels:
      - account
  team@v1:
    root: ./openapi/Team_API.json
    labels:
      - team
extends:
  - recommended
rules:
  no-unused-components: error
features.openapi:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
